# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PrettyWidget' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit', '~> 3.2.0'

end

target 'WidgetDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 3.2.0'

  # Pods for WidgetDemo

  target 'WidgetDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WidgetDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
