# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Apply' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftyJSON', '~> 3.1.4'

  target 'ApplyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ApplyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
